apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
  components:
    aigateway:
      batchGateway: {}
      managementState: Removed
      modelsAsAService:
        managementState: Removed

    aipipelines:
      managementState: Managed

    dashboard:
      managementState: Managed

    feastoperator: {}

    kserve:
      managementState: Managed
      modelsAsService:
        managementState: Removed
      nim:
        airGapped: false
        managementState: Managed
      rawDeploymentServiceConfig: Headed
      wva:
        managementState: Removed

    kueue:
      autoCreateQueues: false
      defaultClusterQueueName: default
      defaultLocalQueueName: default

    llamastackoperator:
      managementState: Managed

    mcplifecycleoperator: {}

    mlflowoperator:
      managementState: Removed

    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries

    ogx:
      managementState: Removed

    ray: {}

    sparkoperator:
      managementState: Removed

    trainer:
      managementState: Removed

    trainingoperator: {}

    trustyai:
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: deny
      mcpGuardrailsMode: false

    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
